// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqyayskeecpsrlntgnxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxeWF5c2tlZWNwc3JsbnRnbnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTMzNjQsImV4cCI6MjA2MDk4OTM2NH0.qfLkxc1Z6Ax2zFzele82qOaBvLf7oOy5P1IWw3InDbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);